---
abstract: 'handling dynamic table for DBIx::Skinny'
author:
  - 'Keiji Yoshimi <walf443 at gmail dot com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Install::ReadmeFromPod: 0
  Test::LoadAllModules: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Skinny-ProxyTable
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  DBIx::Skinny: 0
  Filter::Util::Call: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/walf443/p5-dbix-skinny-proxy_table.git
version: 0.05
